# Generated by Django 4.2.30 on 2026-07-02 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Denumire obiect')),
                ('inventory_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Număr de inventar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriere')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantitate')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/', verbose_name='Fotografie obiect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Responsabil / Deținător')),
            ],
            options={
                'verbose_name': 'Obiect Inventar',
                'verbose_name_plural': 'Obiecte Inventar',
                'ordering': ['-created_at'],
            },
        ),
    ]
