# Generated by Django 4.2.30 on 2026-07-17 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualECC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terminal_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Terminal')),
                ('oficiu', models.CharField(db_index=True, max_length=100, verbose_name='Oficiu')),
                ('nr_fabricatie', models.CharField(db_index=True, max_length=100, verbose_name='Număr de fabricație')),
                ('nr_inregistrare_sfs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nr. înregistrare SFS')),
                ('nr_ordine', models.CharField(blank=True, max_length=100, null=True, verbose_name='Număr de ordine')),
                ('data_inregistrare', models.DateField(blank=True, null=True, verbose_name='Data înregistrării')),
                ('denumire_entitate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Denumire entitate')),
                ('idno', models.CharField(blank=True, max_length=50, null=True, verbose_name='IDNO')),
                ('model_ecc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model ECC')),
                ('adresa_ecc', models.TextField(blank=True, null=True, verbose_name='Adresă ECC')),
                ('ip_adresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Adresă')),
                ('encrypted_mev_key', models.TextField(blank=True, null=True, verbose_name='Cheie MEV Criptată')),
                ('status', models.CharField(choices=[('neconfigurat', 'Neconfigurat'), ('in_curs_de_setare', 'În curs de setare'), ('setat', 'Setat')], default='neconfigurat', max_length=50, verbose_name='Statut')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='virtual_ecc_pdfs/', verbose_name='Fișier PDF înregistrare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Echipament de Casă Virtual',
                'verbose_name_plural': 'Echipamente de Casă Virtuale',
                'ordering': ['oficiu', 'terminal_id'],
            },
        ),
    ]
