# Generated by Django 4.2.30 on 2026-07-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_ecc', '0002_seed_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualecc',
            name='nr_fabricatie',
        ),
    ]
