# Generated by Django 4.2.30 on 2026-07-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_ecc', '0003_remove_virtualecc_nr_fabricatie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualecc',
            name='status',
            field=models.CharField(choices=[('neconfigurat', 'Neconfigurat'), ('aplicatie_instalata', 'Aplicație instalată'), ('in_certificare', 'În certificare'), ('certificat', 'Certificat'), ('pus_in_exploatare', 'Pus în exploatare')], default='neconfigurat', max_length=50, verbose_name='Statut'),
        ),
    ]
