# Generated by Django 4.2.30 on 2026-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_ecc', '0004_alter_virtualecc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualecc',
            name='tel_oficiu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Oficiu'),
        ),
    ]
