# Generated by Django 4.2.30 on 2026-08-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_ecc', '0005_add_tel_oficiu'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualecc',
            name='z_raport',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Z Raport'),
        ),
    ]
