# Generated by Django 5.1.3 on 2026-08-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_ecc', '0006_virtualecc_z_raport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualecc',
            name='status',
            field=models.CharField(choices=[('neconfigurat', 'Neconfigurat'), ('aplicatie_instalata', 'Aplicație instalată'), ('in_certificare', 'În certificare'), ('certificat', 'Certificat'), ('eroare_certificare', 'Eroare la certificare'), ('pus_in_exploatare', 'Pus în exploatare')], default='neconfigurat', max_length=50, verbose_name='Statut'),
        ),
    ]
