# Generated by Django 5.1.3 on 2026-09-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_ecc', '0008_cleanup_mev_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualecc',
            name='comentarii',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarii'),
        ),
    ]
