# Generated by Django 5.1.3 on 2026-09-15 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_ecc', '0010_cleanup_date_mev_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Denumire raion')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Cod raion')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Culoare UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raion',
                'verbose_name_plural': 'Raioane',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='virtualecc',
            name='raion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecc_list', to='virtual_ecc.raion', verbose_name='Raion'),
        ),
    ]
