# Generated by Django 4.2.30 on 2026-06-16 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDutyBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_to_recover', models.IntegerField(default=0, help_text='Zile lipsite — sâmbete ratate ce trebuie recuperate (lucrate)')),
                ('free_days_available', models.IntegerField(default=0, help_text='Zile libere disponibile — sâmbete lucrate ce nu au fost luate ca liber')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duty_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balanță Serviciu',
                'verbose_name_plural': 'Balanțe Serviciu',
            },
        ),
        migrations.CreateModel(
            name='SaturdayDuty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('label', models.CharField(blank=True, default='', help_text='Ex: Sâmbătă recuperare T1 2026', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_saturday_duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sâmbătă de Serviciu',
                'verbose_name_plural': 'Sâmbete de Serviciu',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DutyActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('saturday_booked', 'A ales sâmbăta de serviciu'), ('saturday_cancelled', 'A anulat sâmbăta de serviciu'), ('free_day_taken', 'A marcat o zi liberă ca luată'), ('balance_adjusted', 'Admin a ajustat balanța'), ('saturday_created', 'Admin a creat o sâmbătă'), ('saturday_deleted', 'Admin a șters o sâmbătă'), ('event_created', 'Admin a creat un eveniment în calendar'), ('event_deleted', 'Admin a șters un eveniment din calendar')], db_index=True, max_length=30)),
                ('free_day_date', models.DateField(blank=True, help_text='Data zilei libere luate (pentru acțiunea free_day_taken)', null=True)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, help_text='Cine a efectuat acțiunea (dacă admin a acționat pentru alt user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('saturday', models.ForeignKey(blank=True, help_text='Sâmbăta implicată în acțiune (dacă e cazul)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='duty_days.saturdayduty')),
                ('user', models.ForeignKey(help_text='Utilizatorul vizat de acțiune (despre cine e vorba)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jurnal Activitate Serviciu',
                'verbose_name_plural': 'Jurnale Activitate Serviciu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('event_date', models.DateField(db_index=True)),
                ('event_type', models.CharField(choices=[('announcement', 'Anunț'), ('meeting', 'Ședință'), ('reminder', 'Reminder'), ('other', 'Altele')], default='announcement', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eveniment Calendar',
                'verbose_name_plural': 'Evenimente Calendar',
                'ordering': ['event_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaturdayBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('saturday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='duty_days.saturdayduty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rezervare Sâmbătă',
                'verbose_name_plural': 'Rezervări Sâmbete',
                'ordering': ['saturday__date'],
                'unique_together': {('saturday', 'user')},
            },
        ),
    ]
