# Generated by Django 4.2.30 on 2026-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_days', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saturdaybooking',
            name='comp_option',
            field=models.CharField(choices=[('recovery', 'Recuperare zi lipsă'), ('decide_later', 'Decide mai târziu'), ('free_day', 'Zi liberă')], default='decide_later', max_length=20),
        ),
        migrations.AddField(
            model_name='saturdaybooking',
            name='recovery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
