# Generated by Django 4.2.30 on 2026-06-16 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duty_days', '0002_saturdaybooking_comp_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyactivitylog',
            name='action',
            field=models.CharField(choices=[('saturday_booked', 'A ales sâmbăta de serviciu'), ('saturday_cancelled', 'A anulat sâmbăta de serviciu'), ('free_day_taken', 'A marcat o zi liberă ca luată'), ('balance_adjusted', 'Admin a ajustat balanța'), ('saturday_created', 'Admin a creat o sâmbătă'), ('saturday_deleted', 'Admin a șters o sâmbătă'), ('event_created', 'Admin a creat un eveniment în calendar'), ('event_deleted', 'Admin a șters un eveniment din calendar'), ('leave_added', 'A adăugat o cerere de concediu'), ('leave_approved', 'Concediu aprobat'), ('leave_rejected', 'Concediu respins'), ('leave_cancelled', 'Concediu anulat/șters')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('rest', 'Concediu de Odihnă'), ('study', 'Concediu de Studii'), ('medical', 'Concediu Medical'), ('unpaid', 'Concediu Fără Plată'), ('other', 'Alt Concediu')], db_index=True, default='rest', max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Ciornă'), ('pending', 'În Așteptare'), ('approved', 'Aprobat'), ('rejected', 'Respins')], db_index=True, default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Cine a creat cererea (poate fi admin pt alt user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Angajatul pentru care este cererea de concediu', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cerere Concediu',
                'verbose_name_plural': 'Cereri Concediu',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='duty_days_l_user_id_24f7c7_idx'), models.Index(fields=['start_date', 'end_date'], name='duty_days_l_start_d_60d63a_idx')],
            },
        ),
    ]
