# Generated by Django 4.2.30 on 2026-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_days', '0003_add_leave_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='saturdaybooking',
            name='free_day_credited',
            field=models.BooleanField(default=False, help_text='Indică dacă această sâmbătă a fost creditată ca zi liberă în balanță'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('rest', 'Concediu de Odihnă'), ('study', 'Concediu de Studii'), ('medical', 'Concediu Medical'), ('unpaid', 'Concediu Fără Plată'), ('other', 'Alt Concediu'), ('absence', 'Absență / Lipsă')], db_index=True, default='rest', max_length=20),
        ),
    ]
