# Generated by Django 4.2.30 on 2026-05-29 05:18

from django.db import migrations, models

def cleanup_fallback_titles(apps, schema_editor):
    PasswordVault = apps.get_model('vault', 'PasswordVault')
    from django.db.models import F
    # Reset title to empty string if it matches the organization's name
    PasswordVault.objects.filter(title=F('organization__name')).update(title='')

class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordvault',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.RunPython(cleanup_fallback_titles, reverse_code=migrations.RunPython.noop),
    ]
