# Generated by Django 4.2.30 on 2026-05-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_passwordvault_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordvault',
            name='associated_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
