# Generated by Django 5.1.3 on 2026-08-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta_contacts', '0002_fix_svg_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactoficiu',
            options={'ordering': ['tip', 'ordine', 'oficiu', 'nume'], 'verbose_name': 'Contact Oficiu', 'verbose_name_plural': 'Contacte Oficii'},
        ),
        migrations.AddField(
            model_name='contactoficiu',
            name='ordine',
            field=models.IntegerField(default=0, verbose_name='Ordine afișare'),
        ),
        migrations.AddField(
            model_name='contactoficiu',
            name='tip',
            field=models.CharField(choices=[('inginer', 'Inginer raional'), ('oficiu', 'Contact oficiu')], db_index=True, default='oficiu', max_length=20, verbose_name='Tip contact'),
        ),
        migrations.AlterField(
            model_name='contactoficiu',
            name='oficiu',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Oficiu Poștal'),
        ),
    ]
