# Generated by Django 5.1.3 on 2026-08-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta_contacts', '0003_alter_contactoficiu_options_contactoficiu_ordine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoficiu',
            name='prenume',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prenume'),
        ),
    ]
