# Generated by Django 4.2.30 on 2026-05-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_update_user_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='authentication.permission'),
        ),
    ]
